clc 
clf reset
paranum=2;
defolder='D:\xlj\';
defcolor=[0,0,0];
mch='pbfgj';
no=[0,1,2,3,4];
load('out.mat');
h_fig=figure(1);
set(h_fig,'Menubar','none','name','欢迎使用基于matlab语言的语音情感识别系统',...
    'Numbertitle','off',...
    'color',[0.9023    0.9074    0.8055]);
str1='当前用户名:';
h_text=uicontrol(h_fig,'style','text','unit','normalized',...
    'position',[0.0,0.0,1,1]);


h_text1=uicontrol(h_fig,'style','text','unit','normalized',...
    'position',[0.1,0.9,0.25,0.05],'horizontal','left',...
    'string','请输入用户名:','ForegroundColor',defcolor);
h_edit1=uicontrol(h_fig,'style','edit','unit','normalized',...
    'position',[0.1,0.80,0.25,0.05],'horizontal','left',...
    'ForegroundColor',defcolor,'callback','callback1');

h_text3=uicontrol(h_fig,'style','text','unit','normalized',...
    'position',[0.5,0.8,0.25,0.05],'horizontal','left',...
    'ForegroundColor',defcolor);

h_text4=uicontrol(h_fig,'style','text','unit','normalized',...
    'position',[0.5,0.7,0.25,0.05],'horizontal','left',...
    'ForegroundColor',defcolor);

h_text5=uicontrol(h_fig,'style','text','unit','normalized',...
    'position',[0.5,0.6,0.25,0.05],'horizontal','left',...
    'ForegroundColor',defcolor);

h_text6=uicontrol(h_fig,'style','text','unit','normalized',...
    'position',[0.5,0.5,0.25,0.05],'horizontal','left',...
   'ForegroundColor',defcolor);

h_text7=uicontrol(h_fig,'style','text','unit','normalized',...
    'position',[0.5,0.4,0.25,0.05],'horizontal','left',...
    'ForegroundColor',defcolor);

h_text8=uicontrol(h_fig,'style','text','unit','normalized',...
    'position',[0.5,0.3,0.25,0.05],'horizontal','left',...
    'ForegroundColor',defcolor);

h_text9=uicontrol(h_fig,'style','text','unit','normalized',...
    'position',[0.5,0.2,0.25,0.05],'horizontal','left',...
    'ForegroundColor',defcolor);


h_push2=uicontrol(h_fig,'style','push','unit','normalized',...
    'position',[0.8,0.2,0.18,0.05],'horizontal','left',...
    'string','退出','ForegroundColor',defcolor,'callback','close(figure(1))');




